ALTER TABLE items ADD COLUMN item_code TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN pct_code TEXT NOT NULL DEFAULT '00000000';
ALTER TABLE items ADD COLUMN tax_rate NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN discount NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN further_tax NUMERIC NOT NULL DEFAULT 0;

ALTER TABLE orders ADD COLUMN customer_cnic TEXT;
ALTER TABLE orders ADD COLUMN customer_pntn TEXT;
ALTER TABLE orders ADD COLUMN fiscal_invoice_number TEXT;
ALTER TABLE orders ADD COLUMN fiscal_qr_text TEXT;
ALTER TABLE orders ADD COLUMN fiscal_verification_url TEXT;
